name: Build

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * Sun'

jobs:
  build-image:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        clang_version:
          - '12.0.0'
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.repository_owner}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Meta data
      id: meta
      run: |
        echo "::set-output name=timestamp::$(date --utc +%FT%TZ)"
        echo "::set-output name=source::$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
        echo "::set-output name=revision::$GITHUB_SHA"

        echo "::set-output name=clang_major::$(printenv CLANG_VERSION | cut -d. -f1)"
      env:
        CLANG_VERSION: ${{matrix.clang_version}}
    - name: Build runtime image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        build-args: |
          CLANG_VERSION=${{matrix.clang_version}}
        tags: |
          ghcr.io/hanazuki/clang-tidy:${{matrix.clang_version}}
          ghcr.io/hanazuki/clang-tidy:${{steps.meta.outputs.clang_major}}
        labels: |
          org.opencontainers.image.created=${{steps.meta.outputs.timestamp}}
          org.opencontainers.image.source=${{steps.meta.outputs.source}}
          org.opencontainers.image.revision=${{steps.meta.outputs.revision}}
        push: ${{github.ref == 'refs/heads/master'}}
